In [2]:
import torch
import numpy as np

# 数据类型
torch一共有两套数据类型，分别为在GPU上运行与不在GPU上运行

In [3]:
torch.IntTensor
torch.LongTensor
torch.ByteTensor
torch.FloatTensor
torch.DoubleTensor
# 如果为在GPU上面运行，则为torch.cuda.*

torch.DoubleTensor

# 判断tensor的类型

In [4]:
a = torch.randn(2, 3)
print(a.type())
print(isinstance(a, torch.FloatTensor))
print(isinstance(a, torch.cuda.FloatTensor))

torch.FloatTensor
True
False


# 不同维度的tensor的创建

In [5]:
# Dimension which is 0, is named vector
# It is often used fro Loss
a = torch.tensor(1)
a.type = torch.FloatTensor
print(a)
print(a.shape)
print(a.size())
print(len(a.shape))

tensor(1)
torch.Size([])
torch.Size([])
0


In [6]:
# Dimension which is 1, is named vector. tensor is named here
# It is often used for Bias
# It is also used for Linear Input
a = torch.FloatTensor([1.1, 2.2])
print(a)
print(a.shape)
print(a.size())
print(len(a.shape))

tensor([1.1000, 2.2000])
torch.Size([2])
torch.Size([2])
1


In [7]:
# Dimension which is 2
a = torch.randn(2, 3)
print(a)
print(a.shape)
print(a.size())
print(len(a.shape))

tensor([[-1.7463e+00,  6.3281e-01, -9.4935e-04],
        [-3.0621e-01, -5.8350e-01, -6.2130e-01]])
torch.Size([2, 3])
torch.Size([2, 3])
2


In [8]:
# Dimension which is 3
# It is often used for RNN, which is made for NLP
a = torch.rand(1, 2, 3)
print(a)
print(a.shape)
print(a.size())
print(len(a.shape))

tensor([[[0.2671, 0.2908, 0.5051],
         [0.1113, 0.8172, 0.5334]]])
torch.Size([1, 2, 3])
torch.Size([1, 2, 3])
3


# 工具类shape, numel(), dim()

In [9]:
a = torch.rand(2, 3, 28, 28)
# shape，查看tensor的形状
print(a.shape)
# numel(), 查看数据所占空间的大小，number of element
print(a.numel())
# dim(), 查看tensor的维度
print(a.dim())

torch.Size([2, 3, 28, 28])
4704
4


# 创建tensor

## 使用numpy创建

In [10]:
a = np.array([2, 3, 4])
a = torch.from_numpy(a)
print(a)
print(a.shape)
print(a.type())

tensor([2, 3, 4], dtype=torch.int32)
torch.Size([3])
torch.IntTensor


## 使用list导入

In [11]:
# Tensor给维度（其实也可以给数据）
# tensor给现成的数据
a = torch.Tensor(2, 3)
print(a)
print(a.shape)
print(a.type())
b = torch.tensor([2, 3.2])
print(b)
print(b.shape)
print(b.type())

tensor([[2.5963e+20, 3.3587e-06, 2.6657e-09],
        [2.1061e+23, 1.7203e-04, 1.7470e-04]])
torch.Size([2, 3])
torch.FloatTensor
tensor([2.0000, 3.2000])
torch.Size([2])
torch.FloatTensor


## 使用torch.rand()进行随机采样
> 在[0, 1]之间随机采样

In [12]:
x = torch.rand(2, 3)
print(x)
print(x.shape)
print(x.type())
# like的使用
y = torch.rand_like(x)
print(y)
print(y.shape)
print(y.type())

tensor([[0.8273, 0.1000, 0.4997],
        [0.5372, 0.5678, 0.5191]])
torch.Size([2, 3])
torch.FloatTensor
tensor([[0.0678, 0.3657, 0.4223],
        [0.4250, 0.1339, 0.3958]])
torch.Size([2, 3])
torch.FloatTensor


## 使用torch.randn()进行正态分布随机采样
> randn采样依照正态分布

In [13]:
a = torch.randn(3, 3)
print(a)
print(a.shape)
print(a.type())

tensor([[ 0.3734,  0.1140, -1.0860],
        [-0.7562, -1.4560,  0.8491],
        [-0.7876,  0.8743,  0.1920]])
torch.Size([3, 3])
torch.FloatTensor


## 使用torch.randint()创建整数范围内的tensor

In [14]:
a = torch.randint(1, 10, [3, 3])
print(a)
print(a.shape)
print(a.type())

tensor([[6, 4, 3],
        [7, 6, 7],
        [4, 8, 2]])
torch.Size([3, 3])
torch.LongTensor


## 使用torch.full()创建一个由相同元素组成的tensor

In [15]:
a = torch.full([2, 3], 7)
print(a)
print(a.shape)
print(a.type())

tensor([[7, 7, 7],
        [7, 7, 7]])
torch.Size([2, 3])
torch.LongTensor


## torch.arange()创建一个连续的一维tensor

In [16]:
# [1, 10)
a = torch.arange(1, 10)
print(a)
print(a.shape)
print(a.type())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])
torch.LongTensor


## torch.linspace()与torch.logspace()

In [17]:
# linspace 从0到10分割为10份
a = torch.linspace(0, 10 ,steps=10)
print(a)
print(a.shape)
print(a.type())

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
torch.Size([10])
torch.FloatTensor


In [18]:
# logspace 从10^0到10^-1分成10份，同时还可以改变base
a = torch.logspace(0, -1, steps=10)
b = torch.logspace(0, -1, steps=10, base=2)
print(a)
print(a.shape)
print(a.type())
print(b)
print(b.shape)
print(b.type())

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])
torch.Size([10])
torch.FloatTensor
tensor([1.0000, 0.9259, 0.8572, 0.7937, 0.7349, 0.6804, 0.6300, 0.5833, 0.5400,
        0.5000])
torch.Size([10])
torch.FloatTensor


## 使用torch.ones()和torch.zeros()以及torch.eye(）创建tensor

In [19]:
# 这个也以torch.*_like()
print(torch.ones(3 ,3))
print(torch.zeros(3, 3))
print(torch.eye(3, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## 使用torch.randperm()生成打乱的下标

In [20]:
#生成打乱的0到9
print(torch.randperm(10))

tensor([1, 0, 5, 4, 2, 3, 8, 9, 7, 6])


# 对tensor进行索引以及切片

## 索引的使用

In [21]:
a = torch.rand(4, 3, 28, 28)
print(a[0].shape)
print(a[0, 1].shape)
print(a[:2].shape)
print(a[:2, :-1].shape)
print(a[:2, :, 0::2, 0::2].shape)

torch.Size([3, 28, 28])
torch.Size([28, 28])
torch.Size([2, 3, 28, 28])
torch.Size([2, 2, 28, 28])
torch.Size([2, 3, 14, 14])


## torch.index_select(input, dim, index, out=None)进行tensor的切片

In [22]:
a = torch.arange(0, 9)
print(a)
# 获取tensor a的第一个维度且索引号为2和3的张量子集
print(torch.index_select(a, dim=0, index=torch.tensor([2, 3])))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([2, 3])


In [23]:
b = torch.arange(0, 9).view([3, 3])
print(b)
# 获取tensor b的第二个维度的索引号为0和1的张量子集
print(torch.index_select(b, dim=1, index=torch.tensor([0, 1])))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1],
        [3, 4],
        [6, 7]])


## 用...表示任意多的

In [24]:
a = torch.randint(1, 10, [1, 2, 3, 4, 5])
print(a.shape)
print(a[..., :-1].shape)

torch.Size([1, 2, 3, 4, 5])
torch.Size([1, 2, 3, 4, 4])


## 使用masked_select()通过mask选择相应位置的元素

In [25]:
x = torch.randn(3, 4)
print(x)
mask = x.ge(0.5)
print(mask)
print(torch.masked_select(x, mask))

tensor([[ 1.1300, -0.0698,  1.0953, -0.2350],
        [-2.9467, -1.2536, -1.2334,  0.3912],
        [-0.1170,  0.8351, -0.1934, -0.1575]])
tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False,  True, False, False]])
tensor([1.1300, 1.0953, 0.8351])


## 使用take将数据打一维后，按照索引选取元素

In [26]:
src = torch.tensor([[4, 3, 5],                   [6, 7, 8]])
print(src.shape)
print(torch.take(src, torch.tensor([0, 2, 5])))

torch.Size([2, 3])
tensor([4, 5, 8])


# 维度变换

## 使用view进行维度的变换

In [27]:
a = torch.rand(4, 1, 28, 28)
print(a.shape)
print(a.view(4, 28*28).shape)
print(a.view(4*28, 28).shape)

torch.Size([4, 1, 28, 28])
torch.Size([4, 784])
torch.Size([112, 28])


## 使用squeeze()进行维度的挤压
> 压缩的时候，会将1维度压缩，但是如果维度不是1，就会爆出不变

In [28]:
a = torch.rand(4, 1, 28, 28)
print(a.squeeze().shape)
print(a.squeeze(1).shape)

torch.Size([4, 28, 28])
torch.Size([4, 28, 28])


## 使用unsqueeze()进行维度扩张

In [29]:
a = torch.rand(4, 28, 28)
print(a.unsqueeze(1).shape)

torch.Size([4, 1, 28, 28])


## 使用expand()进行维度的扩张

In [30]:
a = torch.rand(2, 1, 1)
print(a.shape)
print(a.expand(2, 10, 1).shape)

torch.Size([2, 1, 1])
torch.Size([2, 10, 1])


## 使用repeat()进行维度的扩张
>沿着指定的维度重复tensor。不同与expand()，本函数复制的是tensor中的数据。

In [31]:
a = torch.rand(2, 1)
b = a.repeat(2, 2)
print(a)
print(b)

tensor([[0.2409],
        [0.6011]])
tensor([[0.2409, 0.2409],
        [0.6011, 0.6011],
        [0.2409, 0.2409],
        [0.6011, 0.6011]])


## 使用.t()进行矩阵的转置

In [32]:
a = torch.tensor([[1, 2],
                 [3, 4]])
print(a)
print(a.t())

tensor([[1, 2],
        [3, 4]])
tensor([[1, 3],
        [2, 4]])


## 使用transpose()进行维度的交换

In [33]:
a = torch.rand(1, 2)
print(a)
print(a.shape)
b = a.transpose(0, 1)
print(b)
print(b.shape)

tensor([[0.3132, 0.4367]])
torch.Size([1, 2])
tensor([[0.3132],
        [0.4367]])
torch.Size([2, 1])


## 使用permute()进行tensor维度换位
> 与transpose相比，permute可以用于高维矩阵的转换，而transpose只能进行二维矩阵的置换

In [34]:
x = torch.randn(2, 3, 5)
print(x.shape)
print(x.permute(2, 0, 1).shape)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


## 关于contiguous
https://zhuanlan.zhihu.com/p/64551412
> contiguous的作用是让tensor的内存变得连续

为什么需要contiguous?
1. torch.view等操作需要连续的Tensor
2. 处于性能的考虑

# BroadCasting

# 合并与分割

# 数学运算

# 统计属性

## 使用norm()求范数
1. Vector norm
$$
||x||_{p} = (\sum_{i=1}^{n}{|x_i|}^{p})^{1/p}
$$
2. Matrix norm
    
    1-范数：
$$
||A||_1 = \mathop{max}\limits_{j}\sum_{i=1}^{n}|a_{i,j}|
$$
    2-范数：
$$
||A||_2 = \sqrt{\lambda_1} \quad\quad[其中\lambda为A^TA的最大特征值]
$$
F-范数：Frobenius范数，即矩阵元素绝对值的平方和再开方
$$
||A||_F = \sqrt{\sum_{i=1}^{m}\sum_{j=1}^{n}|a_{i, j}|^2)}
$$

In [35]:
a = torch.full([8], 1.)
print(a.type)
b = a.view(2, 4)
c = a. view(2, 2, 2)
# 求a, b, c的1-范式
a.norm(1), b.norm(1), c.norm(1)

<built-in method type of Tensor object at 0x00000191594C6548>


(tensor(8.), tensor(8.), tensor(8.))

In [36]:
# 求a, b, c的2-范式
a.norm(2), b.norm(2), c.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

In [37]:
# 对b的一维度求1-范数
b.norm(1, dim=1)

tensor([4., 4.])

In [38]:
# 对b的一维度求2-范数
b.norm(2, dim=0)

tensor([1.4142, 1.4142, 1.4142, 1.4142])

In [39]:
#对哪个维度求范数，得到的结果的shape是消去这个维度的shape
c.norm(1, dim=1)

tensor([[2., 2.],
        [2., 2.]])

In [40]:
c.norm(2, dim=0)

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

## mean，sum，min，max，prod

In [41]:
a = torch.arange(8).view(2,4).float()
# prod返回新的张量，其中包括输入张量input中指定维度dim中每行的乘积
a.min(), a.max(), a.mean(), a.prod(), a.sum()

(tensor(0.), tensor(7.), tensor(3.5000), tensor(0.), tensor(28.))

In [42]:
#注意这个结果，是原来的tensor打平后的索引
print(a.argmax(), a.argmin())
#如果要求某一个维度的索引，加上dim
print(a)
print(a.argmax(dim=0))

tensor(7) tensor(0)
tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])
tensor([1, 1, 1, 1])


## dim, keepdim
>keepdim保持dimension不发生变化

In [43]:
a = torch.randn(4, 10)
# 出来的结果，前者为最大值，后面是对应的索引
print(a.max(dim=1))

torch.return_types.max(
values=tensor([2.3888, 1.3834, 1.2374, 1.8031]),
indices=tensor([2, 5, 0, 0]))


In [44]:
# keepdim的使用
print(a.max(dim=1).values.shape)
print(a.max(dim=1, keepdim=True).values.shape)

torch.Size([4])
torch.Size([4, 1])


## topk, kthvalue

In [45]:
a = torch.randperm(10).view(2, 5)
print(a)
# 找到某个维度下最大的k个数
print(a.topk(3, dim=1))
# 找到某个维度下最小的k个数
print(a.topk(3, dim=1, largest=False))

tensor([[8, 9, 0, 6, 2],
        [1, 5, 7, 4, 3]])
torch.return_types.topk(
values=tensor([[9, 8, 6],
        [7, 5, 4]]),
indices=tensor([[1, 0, 3],
        [2, 1, 3]]))
torch.return_types.topk(
values=tensor([[0, 2, 6],
        [1, 3, 4]]),
indices=tensor([[2, 4, 3],
        [0, 4, 3]]))


In [46]:
# kthvalue默认为最小，并且不可以改变, 找到第k小并且返回
print(a)
print(a.kthvalue(1, dim=1))

tensor([[8, 9, 0, 6, 2],
        [1, 5, 7, 4, 3]])
torch.return_types.kthvalue(
values=tensor([0, 1]),
indices=tensor([2, 0]))


## compare的运算

In [47]:
# >, >=, <, <=, !=, ==

In [48]:
# eq和equal他们前者返回每一位是否相同，后者返回整体是否相同
a = torch.tensor([1, 2, 3])
b = a
print(torch.eq(a, b))
print(torch.equal(a, b))

tensor([True, True, True])
True


# 高阶操作

## torch.where(condition, x, y)
> 从x和y中选择来源，返回一个新的tensor.
> 其中condition是一个选择，是true or false

In [57]:
cond = torch.tensor([[0.6, 0.7],
                    [0.8, 0.4]])
b = torch.ones(2, 2)
a = torch.zeros(2, 2)
torch.where(cond>0.5, a, b)

tensor([[1., 1.],
        [1., 0.]])

## torch.gather(input, dim, index, out=None) →Tensor
> Gathers values along an axis specified by dim \
查表

In [63]:
prob = torch.rand(4, 10)
print(prob)
idx = prob.topk(dim=1, k=3)[1]
print(idx)
label = torch.arange(10)+100
print(label)
torch.gather(label.expand(4, 10), dim=1, index=idx.long())

tensor([[0.4792, 0.0788, 0.1425, 0.3935, 0.1943, 0.2078, 0.6045, 0.9608, 0.5853,
         0.9396],
        [0.7473, 0.1507, 0.8077, 0.4284, 0.1259, 0.3927, 0.4057, 0.9557, 0.6745,
         0.1057],
        [0.2822, 0.6394, 0.3679, 0.8634, 0.7002, 0.4668, 0.8619, 0.0093, 0.8775,
         0.2737],
        [0.8357, 0.2650, 0.0732, 0.4544, 0.3893, 0.3816, 0.5751, 0.8035, 0.1881,
         0.6178]])
tensor([[7, 9, 6],
        [7, 2, 0],
        [8, 3, 6],
        [0, 7, 9]])
tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])


tensor([[107, 109, 106],
        [107, 102, 100],
        [108, 103, 106],
        [100, 107, 109]])